version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
      
volumes:
  data: